apiVersion: v1
kind: ServiceAccount
metadata:
  name: packetcapture-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: packetcapture-controller
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: packetcapture-controller
subjects:
- kind: ServiceAccount
  name: packetcapture-controller
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: packetcapture-controller
  apiGroup: rbac.authorization.k8s.io
